/*
 * change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Operaciones.Equipo;
import Operaciones.LlenadoAleatorio;
import Operaciones.Operacionequipo;
import Operaciones.Tecnico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yebrail
 */
public class Equipos extends javax.swing.JDialog {

    public static DefaultTableModel modelo2;

    /**
     * Creates new form Equipos
     */
    public Equipos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String pilas[][] = {};
        String columnas[] = {"Nombre del país participante", "Código FIFA", "Número de mundiales en que ha participado", "Número de goles recibidos en los mundiales anteriores", "Número de goles realizados en el mundial actual ", "Nombre del director técnico"};
        modelo2 = new DefaultTableModel(pilas, columnas);
        tabla2.setModel(modelo2);
        Operacionequipo.mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigofifa = new javax.swing.JTextField();
        goleshechosac = new javax.swing.JTextField();
        nombredeltecnicoactual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numbermundialesparti = new javax.swing.JTextField();
        golesrecibidosa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        namepais = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(25, 255, 0));

        jLabel1.setForeground(new java.awt.Color(0, 255, 3));
        jLabel1.setText("Nombre del país participante");

        jLabel2.setForeground(new java.awt.Color(0, 255, 3));
        jLabel2.setText("Codigo de la fifa");

        jLabel3.setForeground(new java.awt.Color(0, 255, 3));
        jLabel3.setText("Número de goles recibidos en los mundiales anteriores");

        jLabel4.setForeground(new java.awt.Color(0, 255, 3));
        jLabel4.setText("Número de goles realizados en el mundial actual");

        jLabel5.setForeground(new java.awt.Color(0, 255, 3));
        jLabel5.setText("Nombre del director técnic");

        codigofifa.setEditable(false);
        codigofifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigofifaActionPerformed(evt);
            }
        });
        codigofifa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigofifaKeyTyped(evt);
            }
        });

        goleshechosac.setEditable(false);
        goleshechosac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goleshechosacActionPerformed(evt);
            }
        });
        goleshechosac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                goleshechosacKeyTyped(evt);
            }
        });

        nombredeltecnicoactual.setEditable(false);
        nombredeltecnicoactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombredeltecnicoactualActionPerformed(evt);
            }
        });

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre del país participante", "Codigo fifa", "N° mundiales que ha participado", "Número de goles recibidos en los mundiales anteriores", "Número de goles realizados en el mundial actual (Brasil)", "Nombre del director técnico"
            }
        ));
        jScrollPane1.setViewportView(tabla2);

        jLabel7.setFont(new java.awt.Font("L M Sans Demi Cond10", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 234, 5));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bienvendio al mantenimiento de Equipo");

        jLabel8.setForeground(new java.awt.Color(0, 255, 3));
        jLabel8.setText("Número de mundiales en que ha participado");

        numbermundialesparti.setEditable(false);
        numbermundialesparti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbermundialespartiActionPerformed(evt);
            }
        });
        numbermundialesparti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numbermundialespartiKeyTyped(evt);
            }
        });

        golesrecibidosa.setEditable(false);
        golesrecibidosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golesrecibidosaActionPerformed(evt);
            }
        });
        golesrecibidosa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                golesrecibidosaKeyTyped(evt);
            }
        });

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        namepais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namepaisActionPerformed(evt);
            }
        });

        jButton5.setText("Generar en Archivos planos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(183, 183, 183))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigofifa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(namepais)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombredeltecnicoactual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goleshechosac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numbermundialesparti, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(golesrecibidosa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(392, 392, 392))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(37, 37, 37)))
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(370, 370, 370))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namepais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigofifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numbermundialesparti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(golesrecibidosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(goleshechosac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombredeltecnicoactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Operacionequipo.eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Operacionequipo.modificar();
        Operacionequipo.limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        long codig = Integer.parseInt(JOptionPane.showInputDialog("introdusca el codigo de la fifa"));
        Operacionequipo.buscar(codig);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (namepais.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta  el pais");

        } else if (codigofifa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el codigo de la fifa");

        } else if (numbermundialesparti.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero de veces participado");

        } else if (golesrecibidosa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta numero de goles recibidos");

        } else if (goleshechosac.getText().isEmpty()) {
            JOptionPane.showInputDialog(rootPane, "Falta el numero de goles hechos actualmente");
        } else if (nombredeltecnicoactual.getText().isEmpty()) {
            JOptionPane.showInputDialog(rootPane, "Falta el nombre del tecnico");
        }
        Equipo p1 = new Equipo(
                namepais.getText().trim(),
                Long.parseLong(codigofifa.getText().trim()),
                Long.parseLong(numbermundialesparti.getText().trim()),
                Long.parseLong(golesrecibidosa.getText().trim()),
                Long.parseLong(goleshechosac.getText().trim()),
                nombredeltecnicoactual.getText().trim());
        Operacionequipo.crear(p1);
        Operacionequipo.mostrar();
        Operacionequipo.limpiar();
        namepais.requestFocus();
        codigofifa.setEditable(false);
        numbermundialesparti.setEditable(false);
        golesrecibidosa.setEditable(false);
        goleshechosac.setEditable(false);
        nombredeltecnicoactual.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void golesrecibidosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golesrecibidosaActionPerformed
        if (golesrecibidosa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero de goles recibidos ");
            golesrecibidosa.requestFocus();
        } else {
            goleshechosac.setEditable(true);
            goleshechosac.requestFocus();
        }
    }//GEN-LAST:event_golesrecibidosaActionPerformed

    private void numbermundialespartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbermundialespartiActionPerformed
        if (numbermundialesparti.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero de mundiales participados ");
            numbermundialesparti.requestFocus();
        } else {
            golesrecibidosa.setEditable(true);
            golesrecibidosa.requestFocus();
        }
    }//GEN-LAST:event_numbermundialespartiActionPerformed

    private void nombredeltecnicoactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombredeltecnicoactualActionPerformed
        if (nombredeltecnicoactual.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el nombre del TECNICO");
            nombredeltecnicoactual.requestFocus();
        }
    }//GEN-LAST:event_nombredeltecnicoactualActionPerformed

    private void goleshechosacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goleshechosacActionPerformed
        if (goleshechosac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero de goles hechos actualmente ");
            goleshechosac.requestFocus();
        } else {
            nombredeltecnicoactual.setEditable(true);
            nombredeltecnicoactual.requestFocus();
        }
    }//GEN-LAST:event_goleshechosacActionPerformed

    private void codigofifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigofifaActionPerformed
       
        if (codigofifa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el codigo ");
            codigofifa.requestFocus();
        } else {
            numbermundialesparti.setEditable(true);
            numbermundialesparti.requestFocus();
        }
    }//GEN-LAST:event_codigofifaActionPerformed

    private void namepaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namepaisActionPerformed

        
        if (namepais.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el pais ");
            namepais.requestFocus();
        } else {
            codigofifa.setEditable(true);
            codigofifa.requestFocus();
        }

    }//GEN-LAST:event_namepaisActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Operaciones.Operacionequipo.informes();
           JOptionPane.showMessageDialog(rootPane, "Guardados en archivos planos Equipos.xls");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void codigofifaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigofifaKeyTyped
       char d = evt.getKeyChar();
        if (Character.isDigit(d) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_codigofifaKeyTyped

    private void numbermundialespartiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numbermundialespartiKeyTyped
      char d = evt.getKeyChar();
        if (Character.isDigit(d) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_numbermundialespartiKeyTyped

    private void golesrecibidosaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_golesrecibidosaKeyTyped
   char d = evt.getKeyChar();
        if (Character.isDigit(d) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_golesrecibidosaKeyTyped

    private void goleshechosacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_goleshechosacKeyTyped
      char d = evt.getKeyChar();
        if (Character.isDigit(d) == false) {
            evt.consume();
        }
    }//GEN-LAST:event_goleshechosacKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Equipos dialog = new Equipos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField codigofifa;
    public static javax.swing.JTextField goleshechosac;
    public static javax.swing.JTextField golesrecibidosa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField namepais;
    public static javax.swing.JTextField nombredeltecnicoactual;
    public static javax.swing.JTextField numbermundialesparti;
    public static javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
