/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Operaciones.Jugador;
import Operaciones.Operacionjugador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yebrail
 */
public class Jugadores extends javax.swing.JDialog {

    public static DefaultTableModel modelo3;

    /**
     * Creates new form Jugadores
     */
    public Jugadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String pilas[][] = {};
        String columnas[] = {"Nombre", "Numero de pasaporte", "Fecha de nacimiento", "N° Camiseta", "N° Mundiales participados", "Cantidad de goles anotados en el mundial"};
        modelo3 = new DefaultTableModel(pilas, columnas);
        tabla3.setModel(modelo3);
        Operacionjugador.mostrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeropasaporte = new javax.swing.JTextField();
        namejugador = new javax.swing.JTextField();
        fecha2 = new com.toedter.calendar.JDateChooser();
        numbercamisa = new javax.swing.JTextField();
        numberparticy = new javax.swing.JTextField();
        cantidaddedgoles = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(25, 255, 0));

        jLabel1.setForeground(new java.awt.Color(0, 255, 3));
        jLabel1.setText("Nombre del jugador");

        jLabel2.setForeground(new java.awt.Color(0, 255, 3));
        jLabel2.setText("Numero de pasaporte");

        jLabel3.setForeground(new java.awt.Color(0, 255, 3));
        jLabel3.setText("Fecha de nacimiento");

        jLabel4.setForeground(new java.awt.Color(0, 255, 3));
        jLabel4.setText("Número de su camiseta");

        jLabel5.setForeground(new java.awt.Color(0, 255, 3));
        jLabel5.setText("Número de mundiales en que ha participado");

        jLabel6.setForeground(new java.awt.Color(0, 255, 3));
        jLabel6.setText("Cantidad de goles anotados en el mundial.");

        numeropasaporte.setEditable(false);
        numeropasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeropasaporteActionPerformed(evt);
            }
        });

        namejugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejugadorActionPerformed(evt);
            }
        });

        numbercamisa.setEditable(false);
        numbercamisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbercamisaActionPerformed(evt);
            }
        });

        numberparticy.setEditable(false);
        numberparticy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberparticyActionPerformed(evt);
            }
        });

        cantidaddedgoles.setEditable(false);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "jugador", "Numeromde pasaporte", "Fecha de nacimiento", "Número de su camiseta", "Número de mundiales en que ha participado", "Cantidad de goles anotados en el mundial."
            }
        ));
        jScrollPane1.setViewportView(tabla3);

        jLabel7.setFont(new java.awt.Font("L M Sans Demi Cond10", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 231, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bienvendio al mantenimiento de jugadores");

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modifcar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Generar Archivos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3)
                        .addGap(60, 60, 60)
                        .addComponent(jButton4)
                        .addGap(43, 43, 43)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(167, 167, 167))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(179, 179, 179))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel4))
                                                .addGap(157, 157, 157))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addGap(34, 34, 34)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberparticy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeropasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namejugador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numbercamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidaddedgoles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(namejugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numeropasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numbercamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numberparticy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidaddedgoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Operacionjugador.modificar();
        Operacionjugador.limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (namejugador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta Nombre");

        } else if (numeropasaporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero del pasaporte");

        } else if (numbercamisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta pais de origen");

        } else if (numberparticy.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta numero mundiales participados");

        } else if (cantidaddedgoles.getText().isEmpty()) {
            JOptionPane.showInputDialog(rootPane, "Falta el numero de veces tecnico ganador");
        }
        Jugador p1 = new Jugador(
                namejugador.getText().trim(),
                Long.parseLong(numeropasaporte.getText().trim()),
                fecha2.getDate(),
                Long.parseLong(numbercamisa.getText().trim()),
                Long.parseLong(numberparticy.getText().trim()),
                Long.parseLong(cantidaddedgoles.getText().trim()));
        System.out.println(fecha2.getDate().toString());
        Operacionjugador.crear(p1);
        Operacionjugador.mostrar();
        Operacionjugador.limpiar();
        namejugador.requestFocus();
        numeropasaporte.setEditable(false);
        numbercamisa.setEditable(false);
        numberparticy.setEditable(false);
        cantidaddedgoles.setEditable(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        long pasaporte = Integer.parseInt(JOptionPane.showInputDialog("introdusca el numero de pasaporte"));
        Operacionjugador.buscar(pasaporte);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Operacionjugador.eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namejugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejugadorActionPerformed
        if (namejugador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el  nombre del jugador ");
            namejugador.requestFocus();
        } else {
            numeropasaporte.setEditable(true);
            numeropasaporte.requestFocus();
        }
    }//GEN-LAST:event_namejugadorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Operaciones.Operacionjugador.informes();
        JOptionPane.showMessageDialog(rootPane, "Guardados en archivos planos Jugadores.xls");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void numeropasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeropasaporteActionPerformed
        if (numeropasaporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el # pasaporte ");
            numeropasaporte.requestFocus();
        } else {
            numbercamisa.setEditable(true);
            numbercamisa.requestFocus();
        }
    }//GEN-LAST:event_numeropasaporteActionPerformed

    private void numbercamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbercamisaActionPerformed
        if (numbercamisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el # de camiseta ");
            numbercamisa.requestFocus();
        } else {
            numberparticy.setEditable(true);
            numberparticy.requestFocus();
        }
    }//GEN-LAST:event_numbercamisaActionPerformed

    private void numberparticyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberparticyActionPerformed
               if (numberparticy.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el # de mundiales jugados ");
            numberparticy.requestFocus();
        } else {
            cantidaddedgoles.setEditable(true);
            cantidaddedgoles.requestFocus();
        }
    }//GEN-LAST:event_numberparticyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jugadores dialog = new Jugadores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField cantidaddedgoles;
    public static com.toedter.calendar.JDateChooser fecha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField namejugador;
    public static javax.swing.JTextField numbercamisa;
    public static javax.swing.JTextField numberparticy;
    public static javax.swing.JTextField numeropasaporte;
    public static javax.swing.JTable tabla3;
    // End of variables declaration//GEN-END:variables
}
