/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Operaciones.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author yebrail
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() throws ParseException {
        initComponents();
        
 String nombres []={ "Lionel","Radamel","Crisitiano","Augusto","aurea","Aurelio","Aureliano","Aurelio","Baldomero",
"Balduino","Baltasar","Bárbaro","Bartolomé","Basileo","Beatriz","Belén","Beltrán","Benedicto","Benigno","Benjamín","Bernabé","Bernardo","Blanco","Blas","Bonifacio",
"Bruno","Calixto","ozil","Camilo","Carlos","Casiano","Casimiro","Casio","Cayetano","Cayo","Cecilio","Ceferino","Celio","Celso","Cesáreo","Cipriano","Cirilo","Cirino","Ciro",
"Claudio","Cleofás","Clotildo","Colombo","Columba","Columbano","Conrado","Constancio","Constantino","Cosmo","Cristino","Cristóbal","Daciano","Dacio","Dámaso",
"Aarón","Abdón","abel","Abelardo","Abrahán","Acacio","Adalberto","Adán","Adelo","juan","manuel","felipe","camilo","sebastian","santiago","Adelaido","Adolfo","Adón","Adrián","Agustín","Alberto","Albino","Alejandro","Alejo","Alfonso","Alfredo","Alicio","Alipio","Almudena","Alvaro","Amadeo","Amaro","Ambrosio","Amelio","Ananías","Anastasio","Andrés","angel","Anselmo","Antero","Antonio","Aquiles"};

    String paises[]={"Brasil","Croacia","Camerún","México","España",
"Países Bajos","Chile","Australia",
"Colombia","Grecia","Costa de Marfil","Japón",
"Uruguay","Costa Rica","Inglaterra","Italia",
"Suiza","Ecuador","Francia","Honduras",
"Argentina","Bosnia Herzegovina","Irán","Nigeria",
"Alemania","Portugal","Ghana","Estados Unidos",
"Bélgica","Argelia","Rusia","Corea del Sur","panama"};
 
 String apellidos[]={"García","Gallego","Marcos","Miranda","Fernández","Méndez","Izquierdo","Blázquez","González","Vidal","Casado","Rodríguez","Guerrero","Gallardo","Rojas","López","Cruz","Parra",
"Cuesta","Martínez","Vega","Otero","Estévez","Sánchez","Pascual","Arroyo","Aranda","Pérez","Herrero","Franco","Lázaro","Martín","Peña","Sierra","Macías","Gómez","Nieto"
,"Espinosa","Del Río","Ruiz","Campos","Galán","Santamaría","Díaz","Márquez","Montes","Beltrán","Hernández","Fuentes","Andrés","Vargas","Jiménez","Rivas","Plaza","Álvarez",
"Ibáñez","Santiago","Sancho","Moreno","León","Benito","Fuentes","Muñoz","Caballero","Lara","Villanueva","Alonso","Carrasco","Soriano","Rivero","Gutiérrez","Lorenzo",
"Valero","Salas","Romero","Herreras","Villar","Roca","Navarro","Ferrer","Luque","Simón","Domínguez","Cabrera","Bueno","Silva","Torres","Giménez","Martí","Blasco","Vázquez",
"Vicente","Segura","Jurado","Gil","Sáez","Bernal","Costa","martinez","cardenas","santos"};
    
LlenadoAleatorio.creartecnico(paises, nombres, apellidos);
LlenadoAleatorio.crearjugador(paises, nombres, apellidos);
LlenadoAleatorio.crearequipo(paises, nombres, apellidos);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/brasil-mascota-del-mundial-2014-llama-fuleco-L-4zlAog.png"))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/taxes.png"))); // NOI18N
        jMenu1.setText("Mantenimiento ");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Untitled-9-32.png"))); // NOI18N
        jMenuItem1.setText("Equipos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/attendance_list.png"))); // NOI18N
        jMenuItem2.setText("Tecnicos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/school_events (1).png"))); // NOI18N
        jMenuItem3.setText("Jugadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Fifa-Throphy-32.png"))); // NOI18N
        jMenu2.setText("Registros ");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/order_form_online_offer-32 (1).png"))); // NOI18N
        jMenuItem4.setText("Registro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Parcial");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Equipos miequipo = new Equipos(this, true);
        miequipo.setLocationRelativeTo(null);
        miequipo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Jugadores misjugadores = new Jugadores(this, true);
        misjugadores.setLocationRelativeTo(null);
        misjugadores.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Registros misregistros = new Registros(this, true);
        misregistros.setLocationRelativeTo(null);
        misregistros.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tecnicos mitecnico = new Tecnicos(this,true);
        //mitecnico.setLocationRelativeTo(null);
        mitecnico.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Parcial miparcial = new Parcial(this, true);
        miparcial.setLocationRelativeTo(null);
        miparcial.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
