/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Operaciones.Operaciontecnico;
import Operaciones.Tecnico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yebrail
 */
public class Tecnicos extends javax.swing.JDialog {

    public static DefaultTableModel modelo1;

    /**
     * Creates new form Tecnicos
     */
    public Tecnicos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String pilas[][] = {};
        String columnas[] = {"Nombre", "Numero de pasaporte", "País de Origen", "Fecha de nacimiento", "Número de mundiales en que ha participado", "Cantidad de veces que ha sido Técnico como ganador de un mundial"};
        modelo1 = new DefaultTableModel(pilas, columnas);
        tabla1.setModel(modelo1);
        Operaciontecnico.mostrar();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeropasaporte = new javax.swing.JTextField();
        nombredeltecnico = new javax.swing.JTextField();
        fechadenacimiento = new com.toedter.calendar.JDateChooser();
        numermudialesp = new javax.swing.JTextField();
        vecestecnico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paisdeorigen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(25, 255, 0));

        jLabel1.setForeground(new java.awt.Color(0, 255, 3));
        jLabel1.setText("Nombre del tecnico");

        jLabel2.setForeground(new java.awt.Color(0, 255, 3));
        jLabel2.setText("Numero de pasaporte");

        jLabel3.setForeground(new java.awt.Color(0, 255, 3));
        jLabel3.setText("Fecha de nacimiento");

        jLabel5.setForeground(new java.awt.Color(0, 255, 3));
        jLabel5.setText("Número de mundiales en que ha participado");

        jLabel6.setForeground(new java.awt.Color(0, 255, 3));
        jLabel6.setText("Cantidad de veces que ha sido tecnico");

        numeropasaporte.setEditable(false);
        numeropasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeropasaporteActionPerformed(evt);
            }
        });

        nombredeltecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombredeltecnicoActionPerformed(evt);
            }
        });

        numermudialesp.setEditable(false);
        numermudialesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numermudialespActionPerformed(evt);
            }
        });

        vecestecnico.setEditable(false);
        vecestecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vecestecnicoActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tecnico", "Numero de pasaporte", "País de Origen", "Fecha de nacimiento", "Número de mundiales en que ha participado", "Cantidad de veces que ha sido Técnico como ganador de un mundial. "
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jLabel7.setFont(new java.awt.Font("L M Sans Demi Cond10", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 234, 5));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bienvendio al mantenimiento de Tecnico");

        jLabel8.setForeground(new java.awt.Color(0, 255, 3));
        jLabel8.setText("Pais de origen");

        paisdeorigen.setEditable(false);
        paisdeorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisdeorigenActionPerformed(evt);
            }
        });

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Generar ArchivosPlanos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(167, 167, 167))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(183, 183, 183)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numeropasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombredeltecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numermudialesp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fechadenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paisdeorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vecestecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel7)))
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4)
                        .addGap(69, 69, 69)
                        .addComponent(jButton5)
                        .addGap(103, 103, 103)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombredeltecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeropasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(paisdeorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fechadenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numermudialesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vecestecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Operaciontecnico.eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nombredeltecnico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta Nombre");

        } else if (numeropasaporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero del pasaporte");

        } else if (paisdeorigen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta pais de origen");

        } else if (numermudialesp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta numero mundiales participados");

        } else if (vecestecnico.getText().isEmpty()) {
            JOptionPane.showInputDialog(rootPane, "Falta el numero de veces tecnico ganador");
        }
        Tecnico p1 = new Tecnico(
                nombredeltecnico.getText().trim(),
                Long.parseLong(numeropasaporte.getText().trim()),
                paisdeorigen.getText().trim(),
                fechadenacimiento.getDate(),
                Long.parseLong(numermudialesp.getText().trim()),
                Long.parseLong(vecestecnico.getText().trim()));
        Operaciontecnico.crear(p1);
        Operaciontecnico.mostrar();
        Operaciontecnico.limpiar();
        nombredeltecnico.requestFocus();
        numeropasaporte.setEditable(false);
        paisdeorigen.setEditable(false);
        numermudialesp.setEditable(false);
        vecestecnico.setEditable(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        long pasa = Integer.parseInt(JOptionPane.showInputDialog("introdusca el numero de pasaporte"));
        Operaciontecnico.buscar(pasa);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Operaciontecnico.modificar();
        Operaciontecnico.limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nombredeltecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombredeltecnicoActionPerformed
        if (nombredeltecnico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el nombre ");
            nombredeltecnico.requestFocus();
        } else {
            numeropasaporte.setEditable(true);
            numeropasaporte.requestFocus();
        }          
                
    }//GEN-LAST:event_nombredeltecnicoActionPerformed

    private void numeropasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeropasaporteActionPerformed
         if (numeropasaporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el numero de pasaporte ");
            numeropasaporte.requestFocus();
        } else {
            paisdeorigen.setEditable(true);
            paisdeorigen.requestFocus();
        }  
    }//GEN-LAST:event_numeropasaporteActionPerformed

    private void paisdeorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisdeorigenActionPerformed
              if (paisdeorigen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el Pais de origen");
            paisdeorigen.requestFocus();
        } else {
            numermudialesp.setEditable(true);
            numermudialesp.requestFocus();
        }  
    }//GEN-LAST:event_paisdeorigenActionPerformed

    private void numermudialespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numermudialespActionPerformed
              if (numermudialesp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta el Pais de origen");
            numermudialesp.requestFocus();
        } else {
            vecestecnico.setEditable(true);
            vecestecnico.requestFocus();
        } 
    }//GEN-LAST:event_numermudialespActionPerformed

    private void vecestecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vecestecnicoActionPerformed
           if (vecestecnico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Falta SABER CUANTAS VECES FUE TECNICO");
            vecestecnico.requestFocus();
    }
    }//GEN-LAST:event_vecestecnicoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   Operaciontecnico.informes();
       JOptionPane.showMessageDialog(rootPane, "Guardados en archivos planos Tecnicos.xls");

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tecnicos dialog = new Tecnicos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser fechadenacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField nombredeltecnico;
    public static javax.swing.JTextField numermudialesp;
    public static javax.swing.JTextField numeropasaporte;
    public static javax.swing.JTextField paisdeorigen;
    public static javax.swing.JTable tabla1;
    public static javax.swing.JTextField vecestecnico;
    // End of variables declaration//GEN-END:variables
}
